name: quant
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - libcxx=17.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.17
  - pip=25.3
  - python=3.10.18
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
    - beautifulsoup4==4.14.3
    - certifi==2025.11.12
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - contourpy==1.3.2
    - curl-cffi==0.13.0
    - cycler==0.12.1
    - fonttools==4.61.1
    - frozendict==2.4.7
    - idna==3.11
    - kiwisolver==1.4.9
    - matplotlib==3.10.8
    - multitasking==0.0.12
    - numpy==2.2.6
    - packaging==25.0
    - pandas==2.3.3
    - peewee==3.18.3
    - pillow==12.0.0
    - platformdirs==4.5.1
    - protobuf==6.33.2
    - pycparser==2.23
    - pyparsing==3.3.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - requests==2.32.5
    - setuptools==78.1.1
    - six==1.17.0
    - soupsieve==2.8.1
    - typing-extensions==4.15.0
    - tzdata==2025.3
    - urllib3==2.6.2
    - websockets==15.0.1
    - wheel==0.45.1
    - yfinance==1.0

